[profile.default]
solc = '0.8.17'
src = 'contracts'
out = 'out'
#libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'seaport-sol/=contracts/helpers/sol/',
    'seaport-core/=contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/'
]

